### ISSUE TITLE
催更催更

### ISSUE THREAD

**Issue by LeoJhonSong** [GeekRicardo/Snipaste#1]
老哥加油呀! 我一直特别想linux平台能有个类似snipaste的截图/贴图软件. 试了下<code>Ctrl</code> <code>Alt</code> <code>F</code>, 确实可用! 截图, 贴图, 双击鼠标左键关闭贴图, 双指上下滑动缩放, 保存图片都能做到:+1: 透明度变化我没看到怎么操作. 希望能增加复制图片到剪贴板功能:+1:

P.S. 建议写一个简单的README, 我是看了看代码才知道怎么操作的:joy:
如果你需要帮助我很高兴能加入开发

**Comment by Zackhardtoname** [comment]
@LeoJhonSong 大哥你能先贡献个readme吗, 感谢！

**Comment by LeoJhonSong** [comment]
:joy: 我咋帮你写readme啊, 你用的好几个库我都没用过, 我只能大致看懂用法...具体每行含义我不确定我理解得对.
那我试着帮你写个框框出来吧 :joy: 后面的我们再具体沟通

**Comment by LeoJhonSong** [comment]
> @LeoJhonSong 大哥你能先贡献个readme吗, 感谢！

兄弟我并不是这个repo作者呀 :joy: 我不确定我对他的代码理解完全正确
